name: 'Deploy on release tag'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?*
      - v20[0-9][0-9].[0-1]?[1470].*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello world"
